name: usb_platform_interface
description: A common platform interface for the usb plugin.
version: 0.2.0
homepage: https://github.com/yanshouwang/usb

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
