name: usb_android
description: Android implementation of the usb plugin.
version: 0.0.2
homepage: https://github.com/yanshouwang/usb

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  usb_platform_interface: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^10.1.4

flutter:
  plugin:
    implements: usb
    platforms:
      android:
        package: dev.yanshouwang.usb_android
        pluginClass: UsbAndroid
        dartPluginClass: UsbAndroid
